import Handlebars from 'handlebars';
import type { 
  MCPServer, 
  TemplateDefinition, 
  ToolDefinition, 
  ForgeMeta,
} from '@/types';
import { loadConfig } from '@/lib/config';

// ============= Handlebars Helpers =============

Handlebars.registerHelper('json', (context) => JSON.stringify(context, null, 2));
Handlebars.registerHelper('zodType', (type: string) => {
  const mapping: Record<string, string> = {
    string: 'z.string()',
    number: 'z.number()',
    boolean: 'z.boolean()',
    object: 'z.record(z.unknown())',
    array: 'z.array(z.unknown())',
  };
  return mapping[type] || 'z.unknown()';
});
Handlebars.registerHelper('pascalCase', (str: string) => 
  str.split(/[-_]/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('')
);
Handlebars.registerHelper('camelCase', (str: string) => {
  const pascal = str.split(/[-_]/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
});
Handlebars.registerHelper('snakeCase', (str: string) => 
  str.replace(/[-\s]/g, '_').toLowerCase()
);
Handlebars.registerHelper('kebabCase', (str: string) => 
  str.replace(/[_\s]/g, '-').toLowerCase()
);

// ============= Template Sources =============

const SERVER_TEMPLATE = `// {{meta.generated_at}} - Generated by MCP Forge v{{meta.forge_version}}
// Template: {{meta.template}} v{{meta.template_version}}
// Server: {{server_name}}
// Project: {{#if project_schema}}{{project_schema.identity.name}}{{else}}(none){{/if}}

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
{{#if use_http}}
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import express from "express";
{{else}}
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
{{/if}}
import { z } from "zod";
{{#each imports}}
import {{this}};
{{/each}}

// ============= Forge Metadata =============
const __FORGE_META__ = {{{json meta}}};

{{#if project_schema}}
// ============= Project Schema (MANTIC) =============
// This server KNOWS its project. Use PROJECT_SCHEMA to reason about constraints,
// filter suggestions, and ensure alignment with project decisions.
const PROJECT_SCHEMA = {{{json project_schema}}};

// Quick accessors
const PROJECT_NAME = PROJECT_SCHEMA.identity.name;
const PROJECT_MISSION = PROJECT_SCHEMA.identity.mission;
const PROJECT_STACK = PROJECT_SCHEMA.stack;
const PROJECT_CONSTRAINTS = PROJECT_SCHEMA.deltas.constraints;
const PROJECT_DECISIONS = PROJECT_SCHEMA.deltas.decisions;
const PROJECT_RISKS = PROJECT_SCHEMA.deltas.risks;

// Helper: Check if action violates any constraint
function violatesConstraint(action: string): { violates: boolean; constraint?: string } {
  for (const c of PROJECT_CONSTRAINTS) {
    // Simple keyword check - extend as needed
    if (action.toLowerCase().includes('cloud') && c.content.toLowerCase().includes('no cloud')) {
      return { violates: true, constraint: c.content };
    }
    if (action.toLowerCase().includes('training') && c.content.toLowerCase().includes('no ai training')) {
      return { violates: true, constraint: c.content };
    }
  }
  return { violates: false };
}
{{/if}}

// ============= Server Setup =============
const server = new McpServer({
  name: "{{kebabCase server_name}}",
  version: "1.0.0"
});

// ============= Tool Implementations =============
{{#each tools}}

// Tool: {{name}}
server.registerTool(
  "{{snakeCase name}}",
  {
    title: "{{pascalCase name}}",
    description: \`{{description}}\`,
    inputSchema: z.object({
{{#each parameters}}
      {{@key}}: {{zodType type}}{{#if description}}.describe("{{description}}"){{/if}}{{#if default}}.default({{{json default}}}){{/if}}{{#unless required}}.optional(){{/unless}},
{{/each}}
    }).strict(),
    annotations: {
      readOnlyHint: {{#if annotations.readOnlyHint}}true{{else}}false{{/if}},
      destructiveHint: {{#if annotations.destructiveHint}}true{{else}}false{{/if}},
      idempotentHint: {{#if annotations.idempotentHint}}true{{else}}false{{/if}},
      openWorldHint: {{#if annotations.openWorldHint}}true{{else}}true{{/if}},
    }
  },
  async (params) => {
    try {
      // TODO: Implement {{name}}
      // Available: params (validated input)
      {{#if ../project_schema}}
      // Available: PROJECT_SCHEMA, PROJECT_CONSTRAINTS, PROJECT_DECISIONS, etc.
      // Use violatesConstraint(action) to check alignment
      {{/if}}
      
      const result = {
        success: true,
        tool: "{{name}}",
        params,
      };

      return {
        content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
        structuredContent: result
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown error";
      return {
        isError: true,
        content: [{ type: "text", text: \`Error in {{name}}: \${message}\` }]
      };
    }
  }
);
{{/each}}

// ============= Server Startup =============
{{#if use_http}}
async function main() {
  const app = express();
  app.use(express.json());

  app.post('/mcp', async (req, res) => {
    const transport = new StreamableHTTPServerTransport({
      sessionIdGenerator: undefined,
      enableJsonResponse: true
    });
    res.on('close', () => transport.close());
    await server.connect(transport);
    await transport.handleRequest(req, res, req.body);
  });

  const port = parseInt(process.env.PORT || '{{port}}');
  app.listen(port, () => {
    console.error(\`{{server_name}} running on http://localhost:\${port}/mcp\`);
    {{#if project_schema}}
    console.error(\`Project: {{project_schema.identity.name}}\`);
    {{/if}}
  });
}
{{else}}
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("{{server_name}} MCP server running on stdio");
  {{#if project_schema}}
  console.error("Project: {{project_schema.identity.name}}");
  {{/if}}
}
{{/if}}

main().catch((error) => {
  console.error("Server error:", error);
  process.exit(1);
});
`;

const PACKAGE_JSON_TEMPLATE = `{
  "name": "{{kebabCase server_name}}",
  "version": "1.0.0",
  "description": "{{description}}",
  "type": "module",
  "main": "dist/index.js",
  "scripts": {
    "build": "tsc",
    "start": "node dist/index.js",
    "dev": "tsx watch src/index.ts"
  },
  "dependencies": {
    "@modelcontextprotocol/sdk": "^1.0.0",
    "zod": "^3.22.4"{{#each dependencies}},
    "{{this}}": "latest"{{/each}}{{#if use_http}},
    "express": "^4.18.2"{{/if}}
  },
  "devDependencies": {
    "@types/node": "^20.10.0",
    "typescript": "^5.3.2",
    "tsx": "^4.6.2"{{#if use_http}},
    "@types/express": "^4.17.21"{{/if}}
  }
}`;

const TSCONFIG_TEMPLATE = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "declaration": true
  },
  "include": ["src/**/*"]
}`;

const README_TEMPLATE = `# {{server_name}}

{{description}}

## Generated by MCP Forge

- Template: {{meta.template}} v{{meta.template_version}}
- Generated: {{meta.generated_at}}
- Forge Version: {{meta.forge_version}}

## Setup

\`\`\`bash
npm install
npm run build
\`\`\`

## Claude Code Configuration

Add to \`~/.claude/claude_desktop_config.json\`:

\`\`\`json
{
  "mcpServers": {
    "{{kebabCase server_name}}": {
      "command": "node",
      "args": ["<PATH_TO_SERVER>/dist/index.js"],
      "env": {
{{#each variables}}
        "{{@key}}": "{{this}}"{{#unless @last}},{{/unless}}
{{/each}}
      }
    }
  }
}
\`\`\`

## Tools

{{#each tools}}
### {{name}}

{{description}}

**Parameters:**
{{#each parameters}}
- \`{{@key}}\` ({{type}}{{#if required}}, required{{/if}}): {{description}}
{{/each}}

{{/each}}

---

*Generated by MCP Forge v{{meta.forge_version}}*
`;

const ENV_EXAMPLE_TEMPLATE = `# Environment variables for {{server_name}}
{{#each variables}}
{{@key}}={{this}}
{{/each}}
`;

const CLAUDE_CONFIG_TEMPLATE = `{
  "{{kebabCase server_name}}": {
    "command": "node",
    "args": ["{{path}}/dist/index.js"],
    "env": {
{{#each variables}}
      "{{@key}}": "{{this}}"{{#unless @last}},{{/unless}}
{{/each}}
    }
  }
}`;

// ============= Compiled Templates =============

const templates = {
  server: Handlebars.compile(SERVER_TEMPLATE),
  packageJson: Handlebars.compile(PACKAGE_JSON_TEMPLATE),
  tsconfig: Handlebars.compile(TSCONFIG_TEMPLATE),
  readme: Handlebars.compile(README_TEMPLATE),
  envExample: Handlebars.compile(ENV_EXAMPLE_TEMPLATE),
  claudeConfig: Handlebars.compile(CLAUDE_CONFIG_TEMPLATE),
};

// ============= Generator Interface =============

export interface GeneratedFiles {
  'src/index.ts': string;
  'package.json': string;
  'tsconfig.json': string;
  'README.md': string;
  '.env.example': string;
  'claude-config.json': string;
}

export interface GeneratorInput {
  serverName: string;
  description: string;
  template: TemplateDefinition;
  variables: Record<string, string>;
  tools: ToolDefinition[];
  transport: 'stdio' | 'http';
  port?: number;
  projectSchema?: import('@/lib/mantic').ProjectSchema | null;
  modifications?: string[];
}

export function generateServer(input: GeneratorInput): GeneratedFiles {
  const config = loadConfig();
  
  const meta: ForgeMeta = {
    generated_at: new Date().toISOString(),
    template: input.template.name,
    template_version: input.template.version,
    forge_version: config.forge.version,
    parent_server: null,
    contextcommand_project: input.projectSchema?.identity.name || null,
    modifications: input.modifications || [],
  };

  const context = {
    server_name: input.serverName,
    description: input.description,
    meta,
    tools: input.tools,
    variables: input.variables,
    dependencies: input.template.dependencies,
    imports: getImports(input.template),
    use_http: input.transport === 'http',
    port: input.port || 3000,
    project_schema: input.projectSchema,
    path: `./servers/${input.serverName.toLowerCase().replace(/\s+/g, '-')}`,
  };

  return {
    'src/index.ts': templates.server(context),
    'package.json': templates.packageJson(context),
    'tsconfig.json': templates.tsconfig(context),
    'README.md': templates.readme(context),
    '.env.example': templates.envExample(context),
    'claude-config.json': templates.claudeConfig(context),
  };
}

function getImports(template: TemplateDefinition): string[] {
  const imports: string[] = [];
  
  if (template.dependencies.includes('@supabase/supabase-js')) {
    imports.push('{ createClient, SupabaseClient } from "@supabase/supabase-js"');
  }
  
  return imports;
}

// ============= Quick Generation =============

export function generateClaudeConfig(server: MCPServer): string {
  return templates.claudeConfig({
    server_name: server.name,
    variables: server.variables,
    path: server.path,
  });
}

export function generateEnvFile(variables: Record<string, string>): string {
  return Object.entries(variables)
    .map(([key, value]) => `${key}=${value}`)
    .join('\n');
}
